server:
  port: 5555
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    api-a:
      path: /api-a/**
      #      url: http://localhost:9200:/
      service-id: service-hello
    api-b:
      path: /api-b/**
      service-id: service-feign-consumer
  ignored-services: "*"