server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
spring:
  application:
    name: service-hello
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/