server:
  port: 9200
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: service-feign-consumer
  main:
    allow-bean-definition-overriding: true #允许多个service注解相同的FeignClient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" #解决http://localhost:9000/actuator/hystrix.stream无法访问的问题
#SERVICE-HELLO:
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 2000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1